org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configuration-cache=false
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.154.2+26.2
junit_version=5.11.4
mod_version=0.1.0-alpha.1
maven_group=moze_intel.projecte
archives_base_name=projecte-fabric
